/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_ffmpeg07v2_NativeDaemon */

#ifndef _Included_sen_com_ffmpeg07v2_NativeDaemon
#define _Included_sen_com_ffmpeg07v2_NativeDaemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_ffmpeg07v2_NativeDaemon
 * Method:    startDaemon
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sen_com_ffmpeg07v2_NativeDaemon_startDaemon
  (JNIEnv *, jobject, jstring);

void create_pthread_dameon();
void create_dameon();

#ifdef __cplusplus
}
#endif
#endif
